/**
 * Auto-generated by Product Generator CLI
 * Date: 2025-06-23T14:56:20.953Z
 * Author: Steelmade Cloudiary
 *
 * This file is poetic, modular, and DRY.
 */
import { ExtendedProductData } from '../../../product-types';

export const dcProduct: ExtendedProductData = {
  id: 'dc',
  name: 'dc ',
  description: '',
  category: 'chairs',
  seriesId: 'ergonomic series',
  imageUrl: 'https://res.cloudinary.com/dqde19mfs/image/upload/v1750684601/steelmade/chairs/ergonomic-series/dc/ic-342-hb-black.jpg',
  features: [
  "High back and mid back ergonomic support",
  "Premium finishes",
  "Adjustable height, tilt, and armrests",
  "Lumbar support and contoured seat",
  "Sturdy, poetic construction"
],
  variants: [
  {
    "variantId": "hb black",
    "variantName": "hb ",
    "name": "dc  - hb ",
    "imageUrl": "https://res.cloudinary.com/dqde19mfs/image/upload/v1750684601/steelmade/chairs/ergonomic-series/dc/ic-342-hb-black.jpg",
    "description": "mb back"
  }
]
};
